### ISSUE TITLE
'Issue' tab disappears when you click it

### ISSUE THREAD

**Issue by davidread** [okfn/ckanext-issues#16]
There doesn't seem great visual integration of a dataset's issues tab.
The issues tab appears:
![screen shot 2015-04-09 at 11 36 28](https://cloud.githubusercontent.com/assets/307612/7065196/fde9739c-deac-11e4-9b68-45dbceb75db8.png)
but when you click on it the tab concept disappears:
![screen shot 2015-04-09 at 11 36 47](https://cloud.githubusercontent.com/assets/307612/7065200/10bfe1e0-dead-11e4-8bfb-b24ca9acbc76.png)
And its also disorienting that the dataset name is no longer displayed at the top of the sidebar, like it is in all the other tabs. Of course it is in the breadcrumbs, but I don't think that is enough.

I don't really care about the UI as DGU doesn't use it, but just logging it as an issue for others really

**Comment by jqnatividad** [comment]
+1. Already using it and it is disorienting for the user.  Also, the Issues tab doesn't have an icon similar to the other tabs.
