### ISSUE TITLE
Spam / abuse - choose one. marked / notified / state / visible - choose one

### ISSUE THREAD

**Issue by davidread** [okfn/ckanext-issues#21]
There is confusion in the terminology. Is it spam or abuse? If you click "Report abuse" then you get flash message "Notified as spam" and on the issue it says "Marked as spam" and you filter for it using "Spam state visible". Choose one way of describing it and stick to it. Same goes for the code.

There are separate problems here - I consider spam as generally automated garbage. These would be banned. However genuine users occasionally cross the line and advertise, use swear words or are vicious to other users, and we'd want to remove their comment - I'd call that abuse. You could say that spam is also abuse, so maybe we should simply call it 'abuse' everywhere instead of 'spam'?

BTW I believe that the "mark comment as spam" storage needs to be unique to the user, rather than storing it as issue.spam_state for all users. I don't understand why other users would want to see whether someone else has marked it as spam. Then once 2 users have marked a comment as spam, then we have some logic that makes the comment invisible for non-admins (as you have it). When an admin marks it as spam then we believe them and change the state to 'deleted'. An admin needs to be able to see those marked by non-admins as spam and choose whether to say if it is ok or indeed spam. So how about we call what non-admins do as 'reporting comments to admins' (say it is 'reported to admins'), and what admins do is 'confirm abuse' or 'confirm not-abuse'.

**Comment by rgrp** [comment]
I think based on our discussion as you suggest we can follow github and just have "report abuse". If necessary we could have "Report spam or abuse" but i'd vote for simpler option.

On the second point I'm not sure I follow as I'm not so knowledgeable re the code. @joetsoi could you perhaps comment here.

**Comment by joetsoi** [comment]
I'm fine with rationalising the terminology

The second point, I agree in the long term it's better to store uniquely per user, I mentioned before there is nothing to stop single annoyed user continuously clicking, expecting comments to disappear immediately. But, this was the agreed simplest, quickest implementation at the time and spam/reporting is a problem probably worthy of it's own extension (see the latest reported 'site has been hacked' email on the mailing list)

**Comment by davidread** [comment]
I've split off the second point into: https://github.com/okfn/ckanext-issues/issues/44

**Comment by davidread** [comment]
My fave is 'report' and 'abuse'

**Comment by joetsoi** [comment]
still need to remove spam_state on the back end, but all the messages in the controllers have been santised
