### ISSUE TITLE
Simple moderation view

### ISSUE THREAD

**Issue by davidread** [okfn/ckanext-issues#43]
Whilst there is a more extensive bit of work to have some auto-moderation logic and monitor how it is doing: https://github.com/okfn/ckanext-issues/issues/27 , before then it would be helpful to just be able to manually view issues & comments and manually moderate.

The moderator comes along to the "moderate issues/comments" page. Doesn't need facets or tabs. Just a single list of all issues and comments, showing all the user-input fields, to scan through and spot the spam. Then with a single click a moderator can mark any issue/comment as spam.

**Comment by rgrp** [comment]
I guess this is per organization / publisher. My question is again whether we want this in v1 and/or whether this is generic or people want to implement per site (e.g. DGU may want to tie this in with other items). @davidread wdyt?

**Comment by davidread** [comment]
I think this is essential for mvp. Otherwise there is far too much clicking required by an administrator to check for spam.

**Comment by rgrp** [comment]
@davidread ok but for DGU will this be pretty bespoke or is it generic?

**Comment by davidread** [comment]
Am not intending to do any integration with Drupal on this, if that's what you mean. And if you're wondering whether this should go into a separate 'moderation' extension, then maybe, but in the future.
